/** Samo polja potrebna za PDF/email — bez history i velikih nizova. */
export function slimTicketForEmail(ticket) {
  if (!ticket) return ticket;
  const {
    id,
    createdAt,
    customerName,
    customerSurname,
    customerPhone,
    customerEmail,
    deviceName,
    deviceSerial,
    batterySerial,
    chargerSerial,
    osPassword,
    issueDescription,
    notes,
    keepData,
    hasBag,
    bagDescription,
    isWarranty,
    warrantyUntil,
    warrantyInvoice,
    printLocale,
    isVhs,
    vhsCassetteCount,
    vhsCassetteCondition,
    vhsPricePerCassette,
    dispatchNoteNumber,
    partsCost,
    serviceCost,
    clientId,
  } = ticket;

  return {
    id,
    createdAt,
    customerName,
    customerSurname,
    customerPhone,
    customerEmail,
    deviceName,
    deviceSerial,
    batterySerial,
    chargerSerial,
    osPassword,
    issueDescription,
    notes,
    keepData,
    hasBag,
    bagDescription,
    isWarranty,
    warrantyUntil,
    warrantyInvoice,
    printLocale,
    isVhs,
    vhsCassetteCount,
    vhsCassetteCondition,
    vhsPricePerCassette,
    dispatchNoteNumber,
    partsCost,
    serviceCost,
    clientId,
  };
}
